# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_bpd <- function(wild, mut, regionX, regionY) {
    .Call(`_rnasnpRCPP_compute_bpd`, wild, mut, regionX, regionY)
}

rcpp_hello_world <- function() {
    .Call(`_rnasnpRCPP_rcpp_hello_world`)
}

